language: ruby

sudo: false

services:
  - docker

env:
  global:
    - KAFKA_HEAP_OPTS="-Xmx512m -Xms512m"

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem update --system

before_script:
  - docker-compose up -d
  - cd ext && bundle exec rake && cd ..

script:
  - bundle exec rspec --format documentation

after_script:
  - docker-compose stop
